### ISSUE TITLE
server.py Module reports "A Cloud Network Domain is required." when network_info > network_domain value is not defined.

### ISSUE THREAD

**Issue by rhogge-JT** [nttmcp/mcp_collection#13]
The documentation for the nttmcp.mcp.server module discusses defining the network_domain at the top level as an option for the module.

In my scenario i am trying to create a server.

If you define the value at this level only when creating a server the execution will fail with an error  "A Cloud Network Domain is required."

FAILS:
```
  - name: Create a server
    server:
      region: na
      datacenter: NA9
      network_domain: my_cnd
      name: my_server_01
      image: "CentOS 7 64-bit 2 CPU"
      disks:
        - controller_type: scsi
          controller_number: 0
          disk_number: 0
          speed: STANDARD
        - controller_type: scsi
          controller_number: 0
          disk_number: 1
          speed: PROVISIONEDIOPS
          iops: 50
      cpu:
        speed: STANDARD
        count: 1
        coresPerSocket: 2
      network_info:
        primary_nic:
          vlan: my_vlan
    start: True
    wait_for_vmtools: True
    state: present
```

Within the example there is mention of defining the value under `network_info` > `network_domain`, this seems to work:

PASSES:
```
  - name: Create a server
    server:
      region: na
      datacenter: NA9
      network_domain: my_cnd
      name: my_server_01
      image: "CentOS 7 64-bit 2 CPU"
      disks:
        - controller_type: scsi
          controller_number: 0
          disk_number: 0
          speed: STANDARD
        - controller_type: scsi
          controller_number: 0
          disk_number: 1
          speed: PROVISIONEDIOPS
          iops: 50
      cpu:
        speed: STANDARD
        count: 1
        coresPerSocket: 2
      network_info:
        network_domain: my_cnd
        primary_nic:
          vlan: my_vlan
    start: True
    wait_for_vmtools: True
    state: present
```

Looking at the code this section, is only considering the presence of this value under `network_info`:

```
    # Check and load the network configuration for the server
    params['networkInfo'] = {}
    try:
        if 'primary_nic' in network:
            primary_nic = {}
            if 'network_domain' in network:
                params['networkInfo']['networkDomainId'] = (
                    client.get_network_domain_by_name(
                        name=network['network_domain'],
                        datacenter=module.params['datacenter']
                    )['id']
                )
            else:
                module.fail_json(msg='A Cloud Network Domain is required.')
```

**Comment by kensinfield** [comment]
Let me take a look into it. I don't think there are any potential flow on issues from changing this, just need to check a couple of things and if they all check out I will get a fix out for this soon.

**Comment by kensinfield** [comment]
Hi, I tested with both the following Playbooks and now either one works. If you happen to supply the network_domain in both places then it will prefer the one under network_info as being more specific.

```
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: na
  tasks:
  - name:  Create server
    nttmcp.mcp.server:
      region: na
      datacenter: NA9
      name: bugfix_test
      image:  "Ubuntu 18.04 64-bit"
      network_domain: mycnd
      admin_password: "my@password123"
      network_info:
        primary_nic:
          vlan: test_vlan1
        additional_nic:
          - networkAdapter: VMXNET3
            vlan: test_vlan
```


```
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: na
  tasks:
  - name:  Create server
    nttmcp.mcp.server:
      region: na
      datacenter: NA9
      name: bugfix_test
      image:  "Ubuntu 18.04 64-bit"
      admin_password: "my@password123"
      network_info:
        network_domain: mycnd
        primary_nic:
          vlan: test_vlan1
        additional_nic:
          - networkAdapter: VMXNET3
            vlan: test_vlan2
```
